version: '3.7'
services:

  db:
    image: postgres:13.0-alpine
    ports:
      - 5432
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      net:

  backend:
    #image: kancat/foodgram_backend:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
     - static_value:/app/static/
     - media_value:/app/media/
    depends_on:
     - db
    env_file:
     - ./.env
    networks:
      net:
   
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      net:

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    networks:
      net:
volumes:
  data_value:
  static_value:
  media_value:
networks:
  net:
