# Generated by Django 4.2.1 on 2023-05-16 19:55

import django.core.validators
from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='время приготовления рецепта не должно быть < 1 мин.'), django.core.validators.MaxValueValidator(10000, message='время приготовления рецепта не должно быть > 10000 мин.')], verbose_name='Время приготовления рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.models.Tag.validate_color], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[recipes.models.Tag.validate_name], verbose_name='Тэг'),
        ),
    ]
